Hostname "localhost"
FQDNLookup true
Interval 15

LoadPlugin syslog
<Plugin syslog>
	LogLevel info
</Plugin>

LoadPlugin cpu
LoadPlugin df
LoadPlugin disk
LoadPlugin entropy
LoadPlugin exec
LoadPlugin interface
LoadPlugin irq
LoadPlugin load
LoadPlugin memory
LoadPlugin processes
LoadPlugin sensors
LoadPlugin swap
LoadPlugin thermal
LoadPlugin uptime
LoadPlugin users
LoadPlugin write_prometheus

<Plugin df>
	FSType rootfs
	FSType sysfs
	FSType proc
	FSType devtmpfs
	FSType devpts
	FSType tmpfs
	FSType fusectl
	FSType cgroup
	IgnoreSelected true
</Plugin>

<Plugin exec>
	Exec nobody "/etc/collectd/scripts/collectd-nvidia.sh"
</Plugin>

<Plugin write_prometheus>
	Port "9103"
</Plugin>
