{
 "title": "Monitoring",
 "description": "collectd->prometheus->grafana",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "label_values(exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "collectd_sensors_power{exported_instance=~\"$Device\"}",
       "legendFormat": "{{sensors}}"
      }
     ]
    },
    {
     "title": "Thermal",
     "type": "bargauge",
     "gridPos": { "h": 24, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "collectd_thermal_gauge{exported_instance=~\"$Device\"}",
       "legendFormat": "{{thermal}}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "collectd_sensors_voltage{exported_instance=~\"$Device\"}",
       "legendFormat": "{{sensors}}-{{type}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "collectd_sensors_temperature{exported_instance=~\"$Device\"}",
       "legendFormat": "{{sensors}}-{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(cpu) (collectd_cpu_total{exported_instance=~\"$Device\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 22, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (irate(collectd_cpu_total{type=\"idle\", exported_instance=~\"$Device\"}))",
       "legendFormat": "CPU {{cpu}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "avg by (type) (irate(collectd_cpu_total{exported_instance=~\"$Device\"}))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "topk(10, sum by(irq) (rate(collectd_irq_total{exported_instance=~\"$Device\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Load Avarege",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "collectd_load_shortterm{exported_instance=~\"$Device\"}",
       "legendFormat": "Short"
      },
      {
       "expr": "collectd_load_midterm{exported_instance=~\"$Device\"}",
       "legendFormat": "Mid"
      },
      {
       "expr": "collectd_load_longterm{exported_instance=~\"$Device\"}",
       "legendFormat": "Long"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "collectd_uptime{exported_instance=~\"$Device\"}",
       "legendFormat": "Uptime"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(collectd_memory{memory=~\".*\", exported_instance=~\"$Device\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(collectd_memory{memory=\"used\", exported_instance=~\"$Device\"}) * 100) / sum(collectd_memory{exported_instance=~\"$Device\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(collectd_swap{memory=~\".*\", exported_instance=~\"$Device\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(collectd_swap{swap=\"used\", exported_instance=~\"$Device\"}) * 100) / sum(collectd_swap{exported_instance=~\"$Device\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "collectd_memory{exported_instance=~\"$Device\"}",
       "legendFormat": "{{memory}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "collectd_swap{exported_instance=~\"$Device\"}",
       "legendFormat": "{{swap}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "collectd_gpu_gauge{gpu=\"mem_total\", exported_instance=~\"$Device\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(sum(collectd_gpu_gauge{gpu=\"mem_used\", exported_instance=~\"$Device\"}) * 100) / sum(collectd_gpu_gauge{gpu=\"mem_total\", exported_instance=~\"$Device\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "collectd_gpu_gauge{gpu=\"gpu_util\"}",
       "legendFormat": "GPU"
      },
      {
       "expr": "collectd_gpu_gauge{gpu=\"mem_util\"}",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "collectd_gpu_gauge{gpu=\"mem_used\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "collectd_gpu_gauge{gpu=\"power\"}",
       "legendFormat": "GPU"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "collectd_gpu_gauge{gpu=\"temp\"}",
       "legendFormat": "GPU"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disks",
     "type": "stat",
     "gridPos": { "h": 12, "w": 4, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(df) (collectd_df_df_complex{exported_instance=~\"$Device\", df!~\"snap.*|var-lib-docker.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Usage",
     "type": "barchart",
     "gridPos": { "h": 12, "w": 20, "x": 4, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "collectd_df_df_complex{exported_instance=~\"$Device\", type=\"used\", df!~\"snap.*|var-lib-docker.*\"}",
       "legendFormat": "{{df}}"
      }
     ]
    },
    {
     "title": "Read/Write throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(disk) (irate(collectd_disk_disk_octets_read_total{disk!~\"loop.*\"}))",
       "legendFormat": "read-{{disk}}"
      },
      {
       "expr": "sum by(disk) (irate(collectd_disk_disk_octets_write_total{disk!~\"loop.*\"}))",
       "legendFormat": "write-{{disk}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(disk) (irate(collectd_disk_disk_ops_read_total{disk!~\"loop.*\"}))",
       "legendFormat": "read-{{disk}}"
      },
      {
       "expr": "sum by(disk) (irate(collectd_disk_disk_ops_write_total{disk!~\"loop.*\"}))",
       "legendFormat": "write-{{disk}}"
      }
     ]
    },
    {
     "title": "Read/Write total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "collectd_disk_disk_merged_read_total{exported_instance=~\"$Device\"}",
       "legendFormat": "R {{disk}}"
      },
      {
       "expr": "collectd_disk_disk_merged_write_total{exported_instance=~\"$Device\"}",
       "legendFormat": "W {{disk}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_time_read_total)\n/\nirate(collectd_disk_disk_ops_read_total)",
       "legendFormat": "read-{{disk}}"
      },
      {
       "expr": "irate(collectd_disk_disk_time_write_total)\n/\nirate(collectd_disk_disk_ops_write_total)",
       "legendFormat": "write-{{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "collectd_processes_ps_state{exported_instance=~\"$Device\"}",
       "legendFormat": "{{processes}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "collectd_processes_ps_count_threads{exported_instance=\"$Device\"}",
       "legendFormat": "{{processes}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(irate(collectd_processes_ps_cputime_user_total{exported_instance=~\"$Device\"}[5m])+ irate(collectd_processes_ps_cputime_syst_total{exported_instance=~\"$Device\"}[5m]))/1000000*100",
       "legendFormat": "{{processes}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "collectd_processes_ps_rss{exported_instance=~\"$Device\"}",
       "legendFormat": "{{processes}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "collectd_interface_if_errors_rx_total{exported_instance=~\"$Device\"}",
       "legendFormat": "RX e {{interface}}"
      },
      {
       "expr": "collectd_interface_if_errors_tx_total{exported_instance=~\"$Device\"}",
       "legendFormat": "TX e {{interface}}"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "P/s" } },
     "targets": [
      {
       "expr": "rate(collectd_interface_if_packets_rx_total{exported_instance=~\"$Device\"}[5m])",
       "legendFormat": "RX {{interface}}"
      },
      {
       "expr": "rate(collectd_interface_if_packets_tx_total{exported_instance=~\"$Device\"}[$__rate_interval])",
       "legendFormat": "TX {{interface}}"
      }
     ]
    }
   ]
  }
 ]
}